/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsveGldqSwJF4 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: VEGldqSW-jF4/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsveGldqSwJF4
});
