/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: O9cDp8UAVzkN

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicSwitchingLettersMobile.module.css"; // plasmic-import: O9cDp8UAVzkN/css

createPlasmicElementProxy;

export type PlasmicSwitchingLettersMobile__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th";
};
export type PlasmicSwitchingLettersMobile__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
};
type VariantPropType = keyof PlasmicSwitchingLettersMobile__VariantsArgs;
export const PlasmicSwitchingLettersMobile__VariantProps =
  new Array<VariantPropType>("others");

export type PlasmicSwitchingLettersMobile__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingLettersMobile__ArgsType;
export const PlasmicSwitchingLettersMobile__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingLettersMobile__OverridesType = {
  header3?: Flex__<"div">;
};

export interface DefaultSwitchingLettersMobileProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingLettersMobile__RenderFunc(props: {
  variants: PlasmicSwitchingLettersMobile__VariantsArgs;
  args: PlasmicSwitchingLettersMobile__ArgsType;
  overrides: PlasmicSwitchingLettersMobile__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"header3"}
      data-plasmic-override={overrides.header3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header3,
        { [sty.header3others__13Th]: hasVariant($state, "others", "_13Th") }
      )}
    >
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__kaA9P,
          {
            [sty.pothers__1st__kaA9Pzu3TZ]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__ymNo5,
                {
                  [sty.spanothers__10th__ymNo5Qn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__ymNo5DBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__ymNo5BhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__ymNo5Zu3TZ]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__ymNo5Cb6QY]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__ymNo5X4Q3J]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__ymNo5Cb36S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__ymNo5XdWPl]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__ymNo5D8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__ymNo5NqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__ymNo5TT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__ymNo5SrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"I\u2019m not a"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__rJeOa,
                {
                  [sty.spanothers__10th__rJeOaQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__rJeOaDBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__rJeOaBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__rJeOazu3TZ]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__rJeOaCb6QY]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__rJeOaX4Q3J]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__rJeOacb36S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__rJeOaXdWPl]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__rJeOad8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__rJeOaNqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__rJeOatT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__rJeOaSrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"traditional lawyer."}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__nLuIp,
          {
            [sty.pothers__13Th__nLuIp7VIdj]: hasVariant(
              $state,
              "others",
              "_13Th"
            ),
            [sty.pothers__1st__nLuIPzu3TZ]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__m6Ejs,
                {
                  [sty.spanothers__10th__m6EjsQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__m6EjsDBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__m6EjsBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__m6Ejszu3TZ]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__3rd__m6EjsX4Q3J]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__m6Ejscb36S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__m6EjsXdWPl]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__m6Ejsd8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__m6EjsNqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__m6EjstT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__m6EjsSrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Pragmatic,"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__zfePz,
                {
                  [sty.spanothers__10th__zfePzQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__zfePzdBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__zfePzBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__zfePZzu3TZ]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__4th__zfePZcb36S]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__zfePzXdWPl]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__zfePZd8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__zfePznqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__zfePZtT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__zfePzsrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"entrepreneurial "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__mkCgq,
                {
                  [sty.spanothers__10th__mkCgqQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__mkCgqdBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__mkCgqBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__5th__mkCgqXdWPl]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__mkCgQd8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__mkCgqnqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__mkCgQtT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__mkCgqsrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"legal support"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__nkVCn,
                {
                  [sty.spanothers__10th__nkVCnQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__nkVCnDBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__nkVCnBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__6th__nkVCnd8CfO]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__nkVCnNqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__nkVCntT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__nkVCnSrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"with heart"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__vc4Hk,
                {
                  [sty.spanothers__10th__vc4HkQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__vc4HkDBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__vc4HkBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__7th__vc4HkNqpAu]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__vc4HktT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__vc4HkSrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"and soul. "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__f2BdL,
                {
                  [sty.spanothers__10th__f2BdLQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__f2BdLdBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__f2BdLBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__8th__f2BdLtT9Nz]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__f2BdLsrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Focused on"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___7Rt2C,
                {
                  [sty.spanothers__10th___7Rt2CQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___7Rt2CDBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___7Rt2CBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__9th___7Rt2CSrSpA]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"clear solutions"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__zyBh,
                {
                  [sty.spanothers__10th__zyBhQn4I]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__zyBhdBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__zyBhBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__zyBHzu3TZ]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                }
              )}
            >
              {"that move"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__dYaJn,
                {
                  [sty.spanothers__11Th__dYaJndBqc]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__dYaJnBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"your business"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__pwVva,
                {
                  [sty.spanothers__12Th__pwVvaBhAxv]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"forward"}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header3: ["header3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingLettersMobile__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingLettersMobile__VariantsArgs;
    args?: PlasmicSwitchingLettersMobile__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingLettersMobile__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingLettersMobile__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingLettersMobile__ArgProps,
          internalVariantPropNames: PlasmicSwitchingLettersMobile__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingLettersMobile__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header3") {
    func.displayName = "PlasmicSwitchingLettersMobile";
  } else {
    func.displayName = `PlasmicSwitchingLettersMobile.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingLettersMobile = Object.assign(
  // Top-level PlasmicSwitchingLettersMobile renders the root element
  makeNodeComponent("header3"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitchingLettersMobile
    internalVariantProps: PlasmicSwitchingLettersMobile__VariantProps,
    internalArgProps: PlasmicSwitchingLettersMobile__ArgProps
  }
);

export default PlasmicSwitchingLettersMobile;
/* prettier-ignore-end */
