/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: GMiZOBrki0Df

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicFaq.module.css"; // plasmic-import: GMiZOBrki0Df/css

import FrameIcon from "./icons/PlasmicIcon__Frame"; // plasmic-import: PGhsVzgFkbUU/icon

createPlasmicElementProxy;

export type PlasmicFaq__VariantMembers = {
  open: "open";
};
export type PlasmicFaq__VariantsArgs = {
  open?: SingleBooleanChoiceArg<"open">;
};
type VariantPropType = keyof PlasmicFaq__VariantsArgs;
export const PlasmicFaq__VariantProps = new Array<VariantPropType>("open");

export type PlasmicFaq__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicFaq__ArgsType;
export const PlasmicFaq__ArgProps = new Array<ArgPropType>("children", "slot");

export type PlasmicFaq__OverridesType = {
  frame515?: Flex__<"div">;
  frame427321884?: Flex__<"div">;
  icon?: Flex__<"div">;
};

export interface DefaultFaqProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFaq__RenderFunc(props: {
  variants: PlasmicFaq__VariantsArgs;
  args: PlasmicFaq__ArgsType;
  overrides: PlasmicFaq__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "open",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.open
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"frame515"}
      data-plasmic-override={overrides.frame515}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.frame515,
        { [sty.frame515open]: hasVariant($state, "open", "open") }
      )}
    >
      <div
        data-plasmic-name={"frame427321884"}
        data-plasmic-override={overrides.frame427321884}
        className={classNames(projectcss.all, sty.frame427321884, {
          [sty.frame427321884open]: hasVariant($state, "open", "open")
        })}
      >
        <div className={classNames(projectcss.all, sty.freeBox__dyTO)}>
          {renderPlasmicSlot({
            defaultContents: (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ibNrI
                )}
              >
                {"Growth & Capital"}
              </div>
            ),
            value: args.children
          })}
        </div>
        <div
          data-plasmic-name={"icon"}
          data-plasmic-override={overrides.icon}
          className={classNames(projectcss.all, sty.icon)}
          onClick={async event => {
            const $steps = {};

            $steps["updateOpen"] = true
              ? (() => {
                  const actionArgs = {
                    vgroup: "open",
                    operation: 2,
                    value: "open"
                  };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    const oldValue = $stateGet($state, vgroup);
                    $stateSet($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateOpen"] != null &&
              typeof $steps["updateOpen"] === "object" &&
              typeof $steps["updateOpen"].then === "function"
            ) {
              $steps["updateOpen"] = await $steps["updateOpen"];
            }
          }}
        >
          <FrameIcon
            className={classNames(projectcss.all, sty.svg__bsNn, {
              [sty.svgopen__bsNn5Rhkd]: hasVariant($state, "open", "open")
            })}
            role={"img"}
          />

          <FrameIcon
            className={classNames(projectcss.all, sty.svg__ovwHy, {
              [sty.svgopen__ovwHy5Rhkd]: hasVariant($state, "open", "open")
            })}
            role={"img"}
          />
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__pmSkr, {
          [sty.freeBoxopen__pmSkr5Rhkd]: hasVariant($state, "open", "open")
        })}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Yv3J,
                  {
                    [sty.textopen___1Yv3J5Rhkd]: hasVariant(
                      $state,
                      "open",
                      "open"
                    )
                  }
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Marina Capital "}
                  </span>
                  <React.Fragment>
                    {
                      "in their investment in Rokksta GmbH through the combination of a\u00a0 convertible loan and a seed round equity investment, including advise on an IP strategy.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Jetpack Studio GmbH"}
                  </span>
                  <React.Fragment>
                    {
                      ", a venture studio, in its formation and the acquisition of multiple portfolio companies through founding investments, convertible loans and/or secondaries.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"Blue Pool Capital"}
                  </span>
                  <React.Fragment>
                    {
                      "*, family office of an Alibaba founder, as lead investor in the \u20ac80 million Series F financing round of GetYourGuide AG, combined with a \u20ac102 million credit facility.\n\n"
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"L\u00f6wenzahn Organics GmbH"}
                  </span>
                  <React.Fragment>
                    {
                      " in connection with the exit of a family office (secondary transaction), the change of its sales model, and the concurrent investment by OysterBay.\n"
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rNo5Z,
                  {
                    [sty.textopen__rNo5Z5Rhkd]: hasVariant(
                      $state,
                      "open",
                      "open"
                    )
                  }
                )}
              >
                {
                  "Wholix GmbH on the negotiation of the first cheque through a bespoke CLA and services for shares advisory structure\n\n\nGlorya GmbH in the entry of late co-founders, the pre-seed financing round, and the professionalization of its IP, employment structures and the implementation of a VSOP.\n\n\nNOBS Holding GmbH in its formation and the entry of founding investors through a bespoke structure.\u00a0\n\nMerlin Digital Solutions GmbH in the entry of a founding investor through the combination of investment and convertible loan, and the optimization of its structural setup, including VSOP and employment law matters."
                }
              </div>
            </React.Fragment>
          ),
          value: args.slot
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame515: ["frame515", "frame427321884", "icon"],
  frame427321884: ["frame427321884", "icon"],
  icon: ["icon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  frame515: "div";
  frame427321884: "div";
  icon: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaq__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaq__VariantsArgs;
    args?: PlasmicFaq__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicFaq__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicFaq__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFaq__ArgProps,
          internalVariantPropNames: PlasmicFaq__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFaq__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame515") {
    func.displayName = "PlasmicFaq";
  } else {
    func.displayName = `PlasmicFaq.${nodeName}`;
  }
  return func;
}

export const PlasmicFaq = Object.assign(
  // Top-level PlasmicFaq renders the root element
  makeNodeComponent("frame515"),
  {
    // Helper components rendering sub-elements
    frame427321884: makeNodeComponent("frame427321884"),
    icon: makeNodeComponent("icon"),

    // Metadata about props expected for PlasmicFaq
    internalVariantProps: PlasmicFaq__VariantProps,
    internalArgProps: PlasmicFaq__ArgProps
  }
);

export default PlasmicFaq;
/* prettier-ignore-end */
