/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: V_odmPGhGYn8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicPoppingScrollAnimation2.module.css"; // plasmic-import: V_odmPGhGYn8/css

createPlasmicElementProxy;

export type PlasmicPoppingScrollAnimation2__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th";
};
export type PlasmicPoppingScrollAnimation2__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
  >;
};
type VariantPropType = keyof PlasmicPoppingScrollAnimation2__VariantsArgs;
export const PlasmicPoppingScrollAnimation2__VariantProps =
  new Array<VariantPropType>("others");

export type PlasmicPoppingScrollAnimation2__ArgsType = {};
type ArgPropType = keyof PlasmicPoppingScrollAnimation2__ArgsType;
export const PlasmicPoppingScrollAnimation2__ArgProps =
  new Array<ArgPropType>();

export type PlasmicPoppingScrollAnimation2__OverridesType = {
  root?: Flex__<"div">;
  bigLawExperience?: Flex__<"div">;
  bigLawExperience2?: Flex__<"div">;
  bigLawExperience3?: Flex__<"div">;
};

export interface DefaultPoppingScrollAnimation2Props {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPoppingScrollAnimation2__RenderFunc(props: {
  variants: PlasmicPoppingScrollAnimation2__VariantsArgs;
  args: PlasmicPoppingScrollAnimation2__ArgsType;
  overrides: PlasmicPoppingScrollAnimation2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootothers__1st]: hasVariant($state, "others", "_1st"),
          [sty.rootothers__5th]: hasVariant($state, "others", "_5th"),
          [sty.rootothers__6th]: hasVariant($state, "others", "_6th")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ywteo)}>
        <div
          data-plasmic-name={"bigLawExperience"}
          data-plasmic-override={overrides.bigLawExperience}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.bigLawExperience,
            {
              [sty.bigLawExperienceothers__10th]: hasVariant(
                $state,
                "others",
                "_10th"
              ),
              [sty.bigLawExperienceothers__1st]: hasVariant(
                $state,
                "others",
                "_1st"
              ),
              [sty.bigLawExperienceothers__2nd]: hasVariant(
                $state,
                "others",
                "_2nd"
              ),
              [sty.bigLawExperienceothers__3rd]: hasVariant(
                $state,
                "others",
                "_3rd"
              ),
              [sty.bigLawExperienceothers__4th]: hasVariant(
                $state,
                "others",
                "_4th"
              ),
              [sty.bigLawExperienceothers__5th]: hasVariant(
                $state,
                "others",
                "_5th"
              ),
              [sty.bigLawExperienceothers__6th]: hasVariant(
                $state,
                "others",
                "_6th"
              ),
              [sty.bigLawExperienceothers__7th]: hasVariant(
                $state,
                "others",
                "_7th"
              ),
              [sty.bigLawExperienceothers__8th]: hasVariant(
                $state,
                "others",
                "_8th"
              ),
              [sty.bigLawExperienceothers__9th]: hasVariant(
                $state,
                "others",
                "_9th"
              )
            }
          )}
        >
          {"Big-Law experience. "}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__zsChv)}>
        <div
          data-plasmic-name={"bigLawExperience2"}
          data-plasmic-override={overrides.bigLawExperience2}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.bigLawExperience2,
            {
              [sty.bigLawExperience2others__10th]: hasVariant(
                $state,
                "others",
                "_10th"
              ),
              [sty.bigLawExperience2others__1st]: hasVariant(
                $state,
                "others",
                "_1st"
              ),
              [sty.bigLawExperience2others__2nd]: hasVariant(
                $state,
                "others",
                "_2nd"
              ),
              [sty.bigLawExperience2others__3rd]: hasVariant(
                $state,
                "others",
                "_3rd"
              ),
              [sty.bigLawExperience2others__4th]: hasVariant(
                $state,
                "others",
                "_4th"
              ),
              [sty.bigLawExperience2others__5th]: hasVariant(
                $state,
                "others",
                "_5th"
              ),
              [sty.bigLawExperience2others__6th]: hasVariant(
                $state,
                "others",
                "_6th"
              ),
              [sty.bigLawExperience2others__7th]: hasVariant(
                $state,
                "others",
                "_7th"
              ),
              [sty.bigLawExperience2others__8th]: hasVariant(
                $state,
                "others",
                "_8th"
              ),
              [sty.bigLawExperience2others__9th]: hasVariant(
                $state,
                "others",
                "_9th"
              )
            }
          )}
        >
          {"Boutique attention. "}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__wxbcC)}>
        <div
          data-plasmic-name={"bigLawExperience3"}
          data-plasmic-override={overrides.bigLawExperience3}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.bigLawExperience3,
            {
              [sty.bigLawExperience3others__10th]: hasVariant(
                $state,
                "others",
                "_10th"
              ),
              [sty.bigLawExperience3others__8th]: hasVariant(
                $state,
                "others",
                "_8th"
              ),
              [sty.bigLawExperience3others__9th]: hasVariant(
                $state,
                "others",
                "_9th"
              )
            }
          )}
        >
          {"Solo-GP accountability."}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "bigLawExperience", "bigLawExperience2", "bigLawExperience3"],
  bigLawExperience: ["bigLawExperience"],
  bigLawExperience2: ["bigLawExperience2"],
  bigLawExperience3: ["bigLawExperience3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  bigLawExperience: "div";
  bigLawExperience2: "div";
  bigLawExperience3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPoppingScrollAnimation2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPoppingScrollAnimation2__VariantsArgs;
    args?: PlasmicPoppingScrollAnimation2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPoppingScrollAnimation2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPoppingScrollAnimation2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPoppingScrollAnimation2__ArgProps,
          internalVariantPropNames: PlasmicPoppingScrollAnimation2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPoppingScrollAnimation2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPoppingScrollAnimation2";
  } else {
    func.displayName = `PlasmicPoppingScrollAnimation2.${nodeName}`;
  }
  return func;
}

export const PlasmicPoppingScrollAnimation2 = Object.assign(
  // Top-level PlasmicPoppingScrollAnimation2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    bigLawExperience: makeNodeComponent("bigLawExperience"),
    bigLawExperience2: makeNodeComponent("bigLawExperience2"),
    bigLawExperience3: makeNodeComponent("bigLawExperience3"),

    // Metadata about props expected for PlasmicPoppingScrollAnimation2
    internalVariantProps: PlasmicPoppingScrollAnimation2__VariantProps,
    internalArgProps: PlasmicPoppingScrollAnimation2__ArgProps
  }
);

export default PlasmicPoppingScrollAnimation2;
/* prettier-ignore-end */
