/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: l8MDZyvChxxV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavItem from "../../NavItem"; // plasmic-import: 7C9jkHgm2lyp/component
import CtaButton from "../../CtaButton"; // plasmic-import: IXgktpxcbfmY/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicNavbar.module.css"; // plasmic-import: l8MDZyvChxxV/css

import MenuSvgrepoComSvgIcon from "./icons/PlasmicIcon__MenuSvgrepoComSvg"; // plasmic-import: m8FVMlxx4LBp/icon
import CloseSvgrepoComSvgIcon from "./icons/PlasmicIcon__CloseSvgrepoComSvg"; // plasmic-import: VrXSeAWGeh3q/icon

createPlasmicElementProxy;

export type PlasmicNavbar__VariantMembers = {
  changes: "scroll";
  open: "open";
};
export type PlasmicNavbar__VariantsArgs = {
  changes?: SingleChoiceArg<"scroll">;
  open?: SingleBooleanChoiceArg<"open">;
};
type VariantPropType = keyof PlasmicNavbar__VariantsArgs;
export const PlasmicNavbar__VariantProps = new Array<VariantPropType>(
  "changes",
  "open"
);

export type PlasmicNavbar__ArgsType = {};
type ArgPropType = keyof PlasmicNavbar__ArgsType;
export const PlasmicNavbar__ArgProps = new Array<ArgPropType>();

export type PlasmicNavbar__OverridesType = {
  navContainer?: Flex__<"div">;
  navbar?: Flex__<"div">;
  navContents?: Flex__<"div">;
  logoContainer?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  span?: Flex__<"div">;
  navItemsContainer?: Flex__<"div">;
  ctaButtonContainer?: Flex__<"div">;
  ctaButton?: Flex__<typeof CtaButton>;
};

export interface DefaultNavbarProps {
  changes?: SingleChoiceArg<"scroll">;
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbar__RenderFunc(props: {
  variants: PlasmicNavbar__VariantsArgs;
  args: PlasmicNavbar__ArgsType;
  overrides: PlasmicNavbar__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "changes",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.changes
      },
      {
        path: "open",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.open
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"navContainer"}
      data-plasmic-override={overrides.navContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.navContainer,
        {
          [sty.navContainerchanges_scroll]: hasVariant(
            $state,
            "changes",
            "scroll"
          ),
          [sty.navContaineropen]: hasVariant($state, "open", "open")
        }
      )}
    >
      <div
        data-plasmic-name={"navbar"}
        data-plasmic-override={overrides.navbar}
        className={classNames(projectcss.all, sty.navbar, {
          [sty.navbaropen]: hasVariant($state, "open", "open")
        })}
      >
        <div
          data-plasmic-name={"navContents"}
          data-plasmic-override={overrides.navContents}
          className={classNames(projectcss.all, sty.navContents)}
        >
          <div
            data-plasmic-name={"logoContainer"}
            data-plasmic-override={overrides.logoContainer}
            className={classNames(projectcss.all, sty.logoContainer)}
          >
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={"logo of evangelisti"}
              className={classNames(sty.img)}
              displayHeight={"42px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"212px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/evangelisti_dev_1/images/asset13X82.png",
                fullWidth: 2569,
                fullHeight: 509,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(projectcss.all, sty.freeBox___04YRw, {
                [sty.freeBoxopen___04YRwBOaAb]: hasVariant(
                  $state,
                  "open",
                  "open"
                )
              })}
              onClick={async event => {
                const $steps = {};

                $steps["updateOpen"] = true
                  ? (() => {
                      const actionArgs = { vgroup: "open", operation: 2 };
                      return (({ vgroup, value }) => {
                        if (typeof value === "string") {
                          value = [value];
                        }

                        const oldValue = $stateGet($state, vgroup);
                        $stateSet($state, vgroup, !oldValue);
                        return !oldValue;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateOpen"] != null &&
                  typeof $steps["updateOpen"] === "object" &&
                  typeof $steps["updateOpen"].then === "function"
                ) {
                  $steps["updateOpen"] = await $steps["updateOpen"];
                }
              }}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox__pIxAv, {
                  [sty.freeBoxopen__pIxAvbOaAb]: hasVariant(
                    $state,
                    "open",
                    "open"
                  )
                })}
              >
                <MenuSvgrepoComSvgIcon
                  className={classNames(projectcss.all, sty.svg__qMtup)}
                  role={"img"}
                />
              </div>
              {(
                hasVariant($state, "open", "open") &&
                hasVariant(globalVariants, "screen", "tablet")
                  ? true
                  : hasVariant(globalVariants, "screen", "tablet")
                    ? true
                    : false
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__pwe3A, {
                    [sty.freeBoxopen__pwe3AbOaAb]: hasVariant(
                      $state,
                      "open",
                      "open"
                    )
                  })}
                >
                  <CloseSvgrepoComSvgIcon
                    className={classNames(projectcss.all, sty.svg___8HFlN)}
                    role={"img"}
                  />
                </div>
              ) : null}
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__uMlL, {
              [sty.freeBoxopen__uMlLBOaAb]: hasVariant($state, "open", "open")
            })}
          >
            <div
              data-plasmic-name={"span"}
              data-plasmic-override={overrides.span}
              className={classNames(projectcss.all, sty.span)}
            />

            <div
              data-plasmic-name={"navItemsContainer"}
              data-plasmic-override={overrides.navItemsContainer}
              className={classNames(projectcss.all, sty.navItemsContainer, {
                [sty.navItemsContaineropen]: hasVariant($state, "open", "open")
              })}
            >
              <NavItem
                className={classNames("__wab_instance", sty.navItem___1AahC)}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem__cTyQz, {
                  [sty.navItemopen__cTyQzbOaAb]: hasVariant(
                    $state,
                    "open",
                    "open"
                  )
                })}
                noicon={true}
                otherLinks={"goldenRules"}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem___8B0QQ)}
                noicon={true}
                otherLinks={"mA"}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem__ilvRn)}
                noicon={true}
                otherLinks={"mittlestand"}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem__gLzxV)}
                noicon={true}
                otherLinks={"venturecapital"}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem__sNlue)}
                noicon={true}
                otherLinks={"startups"}
              />

              <NavItem
                className={classNames("__wab_instance", sty.navItem__izqrr)}
                noicon={true}
                otherLinks={"aboutus"}
              />
            </div>
            <div
              data-plasmic-name={"ctaButtonContainer"}
              data-plasmic-override={overrides.ctaButtonContainer}
              className={classNames(projectcss.all, sty.ctaButtonContainer, {
                [sty.ctaButtonContaineropen]: hasVariant($state, "open", "open")
              })}
            >
              <CtaButton
                data-plasmic-name={"ctaButton"}
                data-plasmic-override={overrides.ctaButton}
                className={classNames("__wab_instance", sty.ctaButton, {
                  [sty.ctaButtonopen]: hasVariant($state, "open", "open")
                })}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navContainer: [
    "navContainer",
    "navbar",
    "navContents",
    "logoContainer",
    "img",
    "span",
    "navItemsContainer",
    "ctaButtonContainer",
    "ctaButton"
  ],
  navbar: [
    "navbar",
    "navContents",
    "logoContainer",
    "img",
    "span",
    "navItemsContainer",
    "ctaButtonContainer",
    "ctaButton"
  ],
  navContents: [
    "navContents",
    "logoContainer",
    "img",
    "span",
    "navItemsContainer",
    "ctaButtonContainer",
    "ctaButton"
  ],
  logoContainer: ["logoContainer", "img"],
  img: ["img"],
  span: ["span"],
  navItemsContainer: ["navItemsContainer"],
  ctaButtonContainer: ["ctaButtonContainer", "ctaButton"],
  ctaButton: ["ctaButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navContainer: "div";
  navbar: "div";
  navContents: "div";
  logoContainer: "div";
  img: typeof PlasmicImg__;
  span: "div";
  navItemsContainer: "div";
  ctaButtonContainer: "div";
  ctaButton: typeof CtaButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavbar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavbar__VariantsArgs;
    args?: PlasmicNavbar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavbar__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavbar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavbar__ArgProps,
          internalVariantPropNames: PlasmicNavbar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navContainer") {
    func.displayName = "PlasmicNavbar";
  } else {
    func.displayName = `PlasmicNavbar.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbar = Object.assign(
  // Top-level PlasmicNavbar renders the root element
  makeNodeComponent("navContainer"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    navContents: makeNodeComponent("navContents"),
    logoContainer: makeNodeComponent("logoContainer"),
    img: makeNodeComponent("img"),
    span: makeNodeComponent("span"),
    navItemsContainer: makeNodeComponent("navItemsContainer"),
    ctaButtonContainer: makeNodeComponent("ctaButtonContainer"),
    ctaButton: makeNodeComponent("ctaButton"),

    // Metadata about props expected for PlasmicNavbar
    internalVariantProps: PlasmicNavbar__VariantProps,
    internalArgProps: PlasmicNavbar__ArgProps
  }
);

export default PlasmicNavbar;
/* prettier-ignore-end */
