/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: 9ZKD6hhnIyjo

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicNewsliding3Cards.module.css"; // plasmic-import: 9ZKD6hhnIyjo/css

createPlasmicElementProxy;

export type PlasmicNewsliding3Cards__VariantMembers = {};
export type PlasmicNewsliding3Cards__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewsliding3Cards__VariantsArgs;
export const PlasmicNewsliding3Cards__VariantProps =
  new Array<VariantPropType>();

export type PlasmicNewsliding3Cards__ArgsType = {};
type ArgPropType = keyof PlasmicNewsliding3Cards__ArgsType;
export const PlasmicNewsliding3Cards__ArgProps = new Array<ArgPropType>();

export type PlasmicNewsliding3Cards__OverridesType = {
  root?: Flex__<"div">;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  card10?: Flex__<"div">;
  card11?: Flex__<"div">;
  card12?: Flex__<"div">;
  card13?: Flex__<"div">;
  card14?: Flex__<"div">;
  card15?: Flex__<"div">;
};

export interface DefaultNewsliding3CardsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewsliding3Cards__RenderFunc(props: {
  variants: PlasmicNewsliding3Cards__VariantsArgs;
  args: PlasmicNewsliding3Cards__ArgsType;
  overrides: PlasmicNewsliding3Cards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {(() => {
        const child$Props = {
          beforeChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "currentSlide",
              ["sliderCarousel", "currentSlide"],
              SliderWrapper_Helpers
            ).apply(null, eventArgs);
          },
          className: classNames("__wab_instance", sty.sliderCarousel),
          initialSlide: generateStateValueProp($state, [
            "sliderCarousel",
            "currentSlide"
          ]),
          ref: ref => {
            $refs["sliderCarousel"] = ref;
          },
          sliderScopeClassName: sty["sliderCarousel__slider"],
          slidesPerRow: hasVariant(globalVariants, "screen", "mobile")
            ? 1
            : hasVariant(globalVariants, "screen", "tablet")
              ? 2
              : 3
        };
        initializeCodeComponentStates(
          $state,
          [
            {
              name: "currentSlide",
              plasmicStateName: "sliderCarousel.currentSlide"
            }
          ],
          [],
          SliderWrapper_Helpers ?? {},
          child$Props
        );

        return (
          <SliderWrapper
            data-plasmic-name={"sliderCarousel"}
            data-plasmic-override={overrides.sliderCarousel}
            {...child$Props}
          >
            <div className={classNames(projectcss.all, sty.freeBox___1Jai)}>
              <div className={classNames(projectcss.all, sty.freeBox__vA555)}>
                <div
                  data-plasmic-name={"card10"}
                  data-plasmic-override={overrides.card10}
                  className={classNames(projectcss.all, sty.card10)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pa7Ci)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fyL2H)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qhtkE
                      )}
                    >
                      {"Bridging valuation gaps"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dexuC
                      )}
                    >
                      {
                        "Call/Put Options, Pragmatic Earn-outs, Vendor Loans and creative risk allocation"
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___2BGo)}>
              <div className={classNames(projectcss.all, sty.freeBox__p1JcG)}>
                <div
                  data-plasmic-name={"card11"}
                  data-plasmic-override={overrides.card11}
                  className={classNames(projectcss.all, sty.card11)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__vZBcH)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__iu5Yl)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uvMwk
                      )}
                    >
                      {"Quick Turnaround Times"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iBlA1
                      )}
                    >
                      {
                        "Along the deal lifecycle. From term sheet to definitive agreements"
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cu24)}>
              <div className={classNames(projectcss.all, sty.freeBox__aVl1U)}>
                <div
                  data-plasmic-name={"card12"}
                  data-plasmic-override={overrides.card12}
                  className={classNames(projectcss.all, sty.card12)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___3Wm6F)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__z2PgP)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rgptK
                      )}
                    >
                      {"Focused DD & executive outputs"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kyRui
                      )}
                    >
                      {"locked-box/MAC calibrated to business reality."}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___5GYwp)}>
              <div className={classNames(projectcss.all, sty.freeBox__moac3)}>
                <div
                  data-plasmic-name={"card13"}
                  data-plasmic-override={overrides.card13}
                  className={classNames(projectcss.all, sty.card13)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__lvhMn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___5CmY)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tdyU9
                      )}
                    >
                      {"Deal Experience\n"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l78Gb
                      )}
                    >
                      {
                        "share/asset deals, carve-outs, spin-offs,\nmergers, Joint Ventures."
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__wI4S8)}>
              <div className={classNames(projectcss.all, sty.freeBox__szes3)}>
                <div
                  data-plasmic-name={"card14"}
                  data-plasmic-override={overrides.card14}
                  className={classNames(projectcss.all, sty.card14)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__uXjWa)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__cq8W)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___92Ltf
                      )}
                    >
                      {"Post-Closing Support.\n "}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wXqFc
                      )}
                    >
                      {
                        "Based on our experience as external general counsel for Mittelstand and start-ups"
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__i3Jtl)}>
              <div className={classNames(projectcss.all, sty.freeBox__gIkD)}>
                <div
                  data-plasmic-name={"card15"}
                  data-plasmic-override={overrides.card15}
                  className={classNames(projectcss.all, sty.card15)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___1KGtk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                      fullWidth: 594,
                      fullHeight: 232,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__iuMsb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bqMCt
                      )}
                    >
                      {"Quick Turnaround Times"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oSmTo
                      )}
                    >
                      {
                        "Along the deal lifecycle. From term sheet to definitive agreements"
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </SliderWrapper>
        );
      })()}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sliderCarousel",
    "card10",
    "card11",
    "card12",
    "card13",
    "card14",
    "card15"
  ],
  sliderCarousel: [
    "sliderCarousel",
    "card10",
    "card11",
    "card12",
    "card13",
    "card14",
    "card15"
  ],
  card10: ["card10"],
  card11: ["card11"],
  card12: ["card12"],
  card13: ["card13"],
  card14: ["card14"],
  card15: ["card15"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sliderCarousel: typeof SliderWrapper;
  card10: "div";
  card11: "div";
  card12: "div";
  card13: "div";
  card14: "div";
  card15: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsliding3Cards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsliding3Cards__VariantsArgs;
    args?: PlasmicNewsliding3Cards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewsliding3Cards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewsliding3Cards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewsliding3Cards__ArgProps,
          internalVariantPropNames: PlasmicNewsliding3Cards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewsliding3Cards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewsliding3Cards";
  } else {
    func.displayName = `PlasmicNewsliding3Cards.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsliding3Cards = Object.assign(
  // Top-level PlasmicNewsliding3Cards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    card10: makeNodeComponent("card10"),
    card11: makeNodeComponent("card11"),
    card12: makeNodeComponent("card12"),
    card13: makeNodeComponent("card13"),
    card14: makeNodeComponent("card14"),
    card15: makeNodeComponent("card15"),

    // Metadata about props expected for PlasmicNewsliding3Cards
    internalVariantProps: PlasmicNewsliding3Cards__VariantProps,
    internalArgProps: PlasmicNewsliding3Cards__ArgProps
  }
);

export default PlasmicNewsliding3Cards;
/* prettier-ignore-end */
