/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: 7C9jkHgm2lyp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicNavItem.module.css"; // plasmic-import: 7C9jkHgm2lyp/css

createPlasmicElementProxy;

export type PlasmicNavItem__VariantMembers = {
  noicon: "noicon";
  otherLinks:
    | "goldenRules"
    | "mA"
    | "mittlestand"
    | "venturecapital"
    | "startups"
    | "aboutus";
};
export type PlasmicNavItem__VariantsArgs = {
  noicon?: SingleBooleanChoiceArg<"noicon">;
  otherLinks?: SingleChoiceArg<
    | "goldenRules"
    | "mA"
    | "mittlestand"
    | "venturecapital"
    | "startups"
    | "aboutus"
  >;
};
type VariantPropType = keyof PlasmicNavItem__VariantsArgs;
export const PlasmicNavItem__VariantProps = new Array<VariantPropType>(
  "noicon",
  "otherLinks"
);

export type PlasmicNavItem__ArgsType = {};
type ArgPropType = keyof PlasmicNavItem__ArgsType;
export const PlasmicNavItem__ArgProps = new Array<ArgPropType>();

export type PlasmicNavItem__OverridesType = {
  navItem?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  text?: Flex__<"div">;
};

export interface DefaultNavItemProps {
  noicon?: SingleBooleanChoiceArg<"noicon">;
  otherLinks?: SingleChoiceArg<
    | "goldenRules"
    | "mA"
    | "mittlestand"
    | "venturecapital"
    | "startups"
    | "aboutus"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavItem__RenderFunc(props: {
  variants: PlasmicNavItem__VariantsArgs;
  args: PlasmicNavItem__ArgsType;
  overrides: PlasmicNavItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "noicon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.noicon
      },
      {
        path: "otherLinks",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.otherLinks
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"navItem"}
      data-plasmic-override={overrides.navItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.navItem
      )}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img, {
          [sty.imgnoicon]: hasVariant($state, "noicon", "noicon")
        })}
        displayHeight={"17px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"36.65234375px"}
        loading={"lazy"}
        src={{
          src: "/plasmic/evangelisti_dev_1/images/group324.svg",
          fullWidth: 36.65234375,
          fullHeight: 17,
          aspectRatio: undefined
        }}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textnoicon]: hasVariant($state, "noicon", "noicon"),
          [sty.textotherLinks_aboutus]: hasVariant(
            $state,
            "otherLinks",
            "aboutus"
          ),
          [sty.textotherLinks_goldenRules]: hasVariant(
            $state,
            "otherLinks",
            "goldenRules"
          ),
          [sty.textotherLinks_mA]: hasVariant($state, "otherLinks", "mA"),
          [sty.textotherLinks_mittlestand]: hasVariant(
            $state,
            "otherLinks",
            "mittlestand"
          ),
          [sty.textotherLinks_startups]: hasVariant(
            $state,
            "otherLinks",
            "startups"
          ),
          [sty.textotherLinks_venturecapital]: hasVariant(
            $state,
            "otherLinks",
            "venturecapital"
          )
        })}
      >
        {hasVariant($state, "otherLinks", "aboutus")
          ? "ABOUT US"
          : hasVariant($state, "otherLinks", "startups")
            ? "STARTUPS"
            : hasVariant($state, "otherLinks", "venturecapital")
              ? "VENTURE CAPITAL"
              : hasVariant($state, "otherLinks", "mittlestand")
                ? "MITTLESTAND"
                : hasVariant($state, "otherLinks", "mA")
                  ? "M&A"
                  : hasVariant($state, "otherLinks", "goldenRules")
                    ? "GOLDEN RULES"
                    : "HOME"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  navItem: ["navItem", "img", "text"],
  img: ["img"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  navItem: "div";
  img: typeof PlasmicImg__;
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavItem__VariantsArgs;
    args?: PlasmicNavItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavItem__ArgProps,
          internalVariantPropNames: PlasmicNavItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "navItem") {
    func.displayName = "PlasmicNavItem";
  } else {
    func.displayName = `PlasmicNavItem.${nodeName}`;
  }
  return func;
}

export const PlasmicNavItem = Object.assign(
  // Top-level PlasmicNavItem renders the root element
  makeNodeComponent("navItem"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicNavItem
    internalVariantProps: PlasmicNavItem__VariantProps,
    internalArgProps: PlasmicNavItem__ArgProps
  }
);

export default PlasmicNavItem;
/* prettier-ignore-end */
