/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: EQWDhZTq_KUf

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicSwitchingcards.module.css"; // plasmic-import: EQWDhZTq_KUf/css

createPlasmicElementProxy;

export type PlasmicSwitchingcards__VariantMembers = {
  others: "_1st";
};
export type PlasmicSwitchingcards__VariantsArgs = {
  others?: SingleChoiceArg<"_1st">;
};
type VariantPropType = keyof PlasmicSwitchingcards__VariantsArgs;
export const PlasmicSwitchingcards__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicSwitchingcards__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingcards__ArgsType;
export const PlasmicSwitchingcards__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingcards__OverridesType = {
  root?: Flex__<"div">;
  sliderCarousel2?: Flex__<typeof SliderWrapper>;
  card10?: Flex__<"div">;
  card9?: Flex__<"div">;
  card8?: Flex__<"div">;
  card11?: Flex__<"div">;
  card12?: Flex__<"div">;
};

export interface DefaultSwitchingcardsProps {
  others?: SingleChoiceArg<"_1st">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingcards__RenderFunc(props: {
  variants: PlasmicSwitchingcards__VariantsArgs;
  args: PlasmicSwitchingcards__ArgsType;
  overrides: PlasmicSwitchingcards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      },
      {
        path: "sliderCarousel2.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel2",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootothers__1st]: hasVariant($state, "others", "_1st") }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__foIHw, {
          [sty.freeBoxothers__1st__foIHwAVmRw]: hasVariant(
            $state,
            "others",
            "_1st"
          )
        })}
      >
        {(() => {
          const child$Props = {
            arrowColor: true ? "rgba(1, 33, 54, 1)" : undefined,
            autoplay: true,
            beforeChange: async (...eventArgs: any) => {
              generateStateOnChangePropForCodeComponents(
                $state,
                "currentSlide",
                ["sliderCarousel2", "currentSlide"],
                SliderWrapper_Helpers
              ).apply(null, eventArgs);
            },
            className: classNames("__wab_instance", sty.sliderCarousel2),
            initialSlide: generateStateValueProp($state, [
              "sliderCarousel2",
              "currentSlide"
            ]),
            ref: ref => {
              $refs["sliderCarousel2"] = ref;
            },
            sliderScopeClassName: sty["sliderCarousel2__slider"]
          };
          initializeCodeComponentStates(
            $state,
            [
              {
                name: "currentSlide",
                plasmicStateName: "sliderCarousel2.currentSlide"
              }
            ],
            [],
            SliderWrapper_Helpers ?? {},
            child$Props
          );

          return (
            <SliderWrapper
              data-plasmic-name={"sliderCarousel2"}
              data-plasmic-override={overrides.sliderCarousel2}
              {...child$Props}
            >
              <div
                className={classNames(projectcss.all, sty.freeBox___3DkWu, {
                  [sty.freeBoxothers__1st___3DkWuAVmRw]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__jnea, {
                    [sty.freeBoxothers__1st__jneaAVmRw]: hasVariant(
                      $state,
                      "others",
                      "_1st"
                    )
                  })}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vfOa2, {
                      [sty.freeBoxothers__1st__vfOa2AVmRw]: hasVariant(
                        $state,
                        "others",
                        "_1st"
                      )
                    })}
                  >
                    <div
                      data-plasmic-name={"card10"}
                      data-plasmic-override={overrides.card10}
                      className={classNames(projectcss.all, sty.card10, {
                        [sty.card10others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__wHcJs, {
                          [sty.imgothers__1st__wHcJsAVmRw]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cJoVs
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___49Jt2
                          )}
                        >
                          {"Bridging valuation gaps"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__aNJmW
                          )}
                        >
                          {
                            "Call/Put Options, Pragmatic Earn-outs, Vendor Loans and creative risk allocation"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__fXId, {
                  [sty.freeBoxothers__1st__fXIdAVmRw]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vf189)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xsOqy)}
                  >
                    <div
                      data-plasmic-name={"card9"}
                      data-plasmic-override={overrides.card9}
                      className={classNames(projectcss.all, sty.card9, {
                        [sty.card9others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___8BC6, {
                          [sty.imgothers__1st___8BC6AVmRw]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lfIGg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k2Xf3
                          )}
                        >
                          {"Quick Turnaround Times"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___74WXr
                          )}
                        >
                          {
                            "Along the deal lifecycle. From term sheet to definitive agreements"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__uDfcg, {
                  [sty.freeBoxothers__1st__uDfcgAVmRw]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__r0TNf)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__v1DlB)}
                  >
                    <div
                      data-plasmic-name={"card8"}
                      data-plasmic-override={overrides.card8}
                      className={classNames(projectcss.all, sty.card8, {
                        [sty.card8others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__yF40, {
                          [sty.imgothers__1st__yF40AVmRw]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___97GK4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ymdAx
                          )}
                        >
                          {"Focused DD & executive outputs"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cYk0X
                          )}
                        >
                          {"locked-box/MAC calibrated to business reality."}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__og4Gd, {
                  [sty.freeBoxothers__1st__og4GdAVmRw]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__k14Gh)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__fn3Ek)}
                  >
                    <div
                      data-plasmic-name={"card11"}
                      data-plasmic-override={overrides.card11}
                      className={classNames(projectcss.all, sty.card11, {
                        [sty.card11others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___3Ubsk, {
                          [sty.imgothers__1st___3UbskAVmRw]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rWtEg
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ceQ01
                          )}
                        >
                          {"Deal Experience"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__na8Z2
                          )}
                        >
                          {
                            "share/asset deals, carve-outs, spin-offs,\nmergers, Joint Ventures."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(projectcss.all, sty.freeBox__x3SAd, {
                  [sty.freeBoxothers__1st__x3SAdAVmRw]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                })}
              >
                <div className={classNames(projectcss.all, sty.freeBox__s7Lye)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qCld8)}
                  >
                    <div
                      data-plasmic-name={"card12"}
                      data-plasmic-override={overrides.card12}
                      className={classNames(projectcss.all, sty.card12, {
                        [sty.card12others__1st]: hasVariant(
                          $state,
                          "others",
                          "_1st"
                        )
                      })}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___6FgIb, {
                          [sty.imgothers__1st___6FgIbAVmRw]: hasVariant(
                            $state,
                            "others",
                            "_1st"
                          )
                        })}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/evangelisti_dev_1/images/rectangle193.svg",
                          fullWidth: 594,
                          fullHeight: 232,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3HIfp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__a9Jl7
                          )}
                        >
                          {"Post-Closing Support. "}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3YuDm
                          )}
                        >
                          {
                            "Based on our experience as external general counsel for Mittelstand and start-ups"
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </SliderWrapper>
          );
        })()}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___7CzTe)}>
        <div
          className={classNames(projectcss.all, sty.freeBox___8IoQm, {
            [sty.freeBoxothers__1st___8IoQmAVmRw]: hasVariant(
              $state,
              "others",
              "_1st"
            )
          })}
        >
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 0;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__m1Gx)}>
              <div className={classNames(projectcss.all, sty.freeBox__gpNr7)} />

              <div className={classNames(projectcss.all, sty.freeBox__fOqt)} />

              <div className={classNames(projectcss.all, sty.freeBox__xAady)} />

              <div className={classNames(projectcss.all, sty.freeBox__urEtW)} />

              <div className={classNames(projectcss.all, sty.freeBox__h3Pm)} />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__lmH9)}>
              <div className={classNames(projectcss.all, sty.freeBox__bQeqv)} />

              <div className={classNames(projectcss.all, sty.freeBox__kxMy9)} />

              <div className={classNames(projectcss.all, sty.freeBox__owwFs)} />

              <div className={classNames(projectcss.all, sty.freeBox__z1Tsf)} />

              <div className={classNames(projectcss.all, sty.freeBox__c0O0X)} />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__ttO1B)}>
              <div className={classNames(projectcss.all, sty.freeBox__j5Du3)} />

              <div className={classNames(projectcss.all, sty.freeBox__hy8Na)} />

              <div className={classNames(projectcss.all, sty.freeBox__mLgz)} />

              <div className={classNames(projectcss.all, sty.freeBox__jr38C)} />

              <div className={classNames(projectcss.all, sty.freeBox__j5EfJ)} />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 3;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox___8M3Oa)}>
              <div className={classNames(projectcss.all, sty.freeBox__zFmNu)} />

              <div className={classNames(projectcss.all, sty.freeBox__oj0K1)} />

              <div className={classNames(projectcss.all, sty.freeBox__cdsYh)} />

              <div className={classNames(projectcss.all, sty.freeBox__c2HfU)} />

              <div className={classNames(projectcss.all, sty.freeBox__fjmXa)} />
            </div>
          ) : null}
          {(() => {
            try {
              return $state.sliderCarousel2.currentSlide === 4;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <div className={classNames(projectcss.all, sty.freeBox__elQSi)}>
              <div className={classNames(projectcss.all, sty.freeBox__noNsJ)} />

              <div className={classNames(projectcss.all, sty.freeBox__vtkLp)} />

              <div className={classNames(projectcss.all, sty.freeBox__bLMk)} />

              <div
                className={classNames(projectcss.all, sty.freeBox___2UGy5)}
              />

              <div
                className={classNames(projectcss.all, sty.freeBox___7Kq0O)}
              />
            </div>
          ) : null}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sliderCarousel2",
    "card10",
    "card9",
    "card8",
    "card11",
    "card12"
  ],
  sliderCarousel2: [
    "sliderCarousel2",
    "card10",
    "card9",
    "card8",
    "card11",
    "card12"
  ],
  card10: ["card10"],
  card9: ["card9"],
  card8: ["card8"],
  card11: ["card11"],
  card12: ["card12"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  sliderCarousel2: typeof SliderWrapper;
  card10: "div";
  card9: "div";
  card8: "div";
  card11: "div";
  card12: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingcards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingcards__VariantsArgs;
    args?: PlasmicSwitchingcards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingcards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingcards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingcards__ArgProps,
          internalVariantPropNames: PlasmicSwitchingcards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingcards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSwitchingcards";
  } else {
    func.displayName = `PlasmicSwitchingcards.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingcards = Object.assign(
  // Top-level PlasmicSwitchingcards renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sliderCarousel2: makeNodeComponent("sliderCarousel2"),
    card10: makeNodeComponent("card10"),
    card9: makeNodeComponent("card9"),
    card8: makeNodeComponent("card8"),
    card11: makeNodeComponent("card11"),
    card12: makeNodeComponent("card12"),

    // Metadata about props expected for PlasmicSwitchingcards
    internalVariantProps: PlasmicSwitchingcards__VariantProps,
    internalArgProps: PlasmicSwitchingcards__ArgProps
  }
);

export default PlasmicSwitchingcards;
/* prettier-ignore-end */
