/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: 4YM-JBXS-hZU

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicSwitchingLetters.module.css"; // plasmic-import: 4YM-JBXS-hZU/css

createPlasmicElementProxy;

export type PlasmicSwitchingLetters__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th";
};
export type PlasmicSwitchingLetters__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
};
type VariantPropType = keyof PlasmicSwitchingLetters__VariantsArgs;
export const PlasmicSwitchingLetters__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicSwitchingLetters__ArgsType = {};
type ArgPropType = keyof PlasmicSwitchingLetters__ArgsType;
export const PlasmicSwitchingLetters__ArgProps = new Array<ArgPropType>();

export type PlasmicSwitchingLetters__OverridesType = {
  header3?: Flex__<"div">;
};

export interface DefaultSwitchingLettersProps {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
    | "_12Th"
    | "_13Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSwitchingLetters__RenderFunc(props: {
  variants: PlasmicSwitchingLetters__VariantsArgs;
  args: PlasmicSwitchingLetters__ArgsType;
  overrides: PlasmicSwitchingLetters__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"header3"}
      data-plasmic-override={overrides.header3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header3,
        { [sty.header3others__13Th]: hasVariant($state, "others", "_13Th") }
      )}
    >
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p__pllcB,
          {
            [sty.pothers__1st__pllcBwDAe]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__w5G,
                {
                  [sty.spanothers__10th__w5GnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__w5GxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__w5G8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__w5GwDAe]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__w5Gmzldo]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__w5GMw3Fi]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__w5Gbp1Vc]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__w5Gf8Nj1]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__w5GbjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__w5GmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__w5Gb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__w5GjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"I\u2019m not a"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__xtmMl,
                {
                  [sty.spanothers__10th__xtmMLnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__xtmMLxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__xtmMl8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__xtmMlwDAe]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__2nd__xtmMLmzldo]: hasVariant(
                    $state,
                    "others",
                    "_2nd"
                  ),
                  [sty.spanothers__3rd__xtmMlMw3Fi]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th__xtmMlbp1Vc]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__xtmMlf8Nj1]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__xtmMlbjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__xtmMLmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__xtmMLb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__xtmMLjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"traditional lawyer."}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
      <p
        className={classNames(
          projectcss.all,
          projectcss.p,
          projectcss.__wab_text,
          sty.p___8Xmnh,
          {
            [sty.pothers__13Th___8Xmnhuqw2P]: hasVariant(
              $state,
              "others",
              "_13Th"
            ),
            [sty.pothers__1st___8XmnhWDAe]: hasVariant($state, "others", "_1st")
          }
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___78Wof,
                {
                  [sty.spanothers__10th___78WoFnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___78WoFxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___78Wof8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st___78WofwDAe]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__3rd___78WofMw3Fi]: hasVariant(
                    $state,
                    "others",
                    "_3rd"
                  ),
                  [sty.spanothers__4th___78Wofbp1Vc]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th___78Woff8Nj1]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th___78WofbjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th___78WoFmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th___78WoFb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th___78WoFjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Pragmatic,"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jEfca,
                {
                  [sty.spanothers__10th__jEfcAnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__jEfcAxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__jEfca8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__jEfcawDAe]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  ),
                  [sty.spanothers__4th__jEfcabp1Vc]: hasVariant(
                    $state,
                    "others",
                    "_4th"
                  ),
                  [sty.spanothers__5th__jEfcaf8Nj1]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__jEfcabjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__jEfcAmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__jEfcAb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__jEfcAjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"entrepreneurial "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jwFGr,
                {
                  [sty.spanothers__10th__jwFGrnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__jwFGrxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__jwFGr8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__5th__jwFGrF8Nj1]: hasVariant(
                    $state,
                    "others",
                    "_5th"
                  ),
                  [sty.spanothers__6th__jwFGrBjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th__jwFGrmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__jwFGrb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__jwFGrjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"legal support"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___5Uxck,
                {
                  [sty.spanothers__10th___5UxcKnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___5UxcKxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___5Uxck8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__6th___5UxckbjCn9]: hasVariant(
                    $state,
                    "others",
                    "_6th"
                  ),
                  [sty.spanothers__7th___5UxcKmNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th___5UxcKb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th___5UxcKjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"with heart"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__xiSf2,
                {
                  [sty.spanothers__10th__xiSf2NFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__xiSf2XdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__xiSf28KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__7th__xiSf2MNgxj]: hasVariant(
                    $state,
                    "others",
                    "_7th"
                  ),
                  [sty.spanothers__8th__xiSf2B5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__xiSf2JynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"and soul. "}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__oiWgM,
                {
                  [sty.spanothers__10th__oiWgMnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__oiWgMxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__oiWgM8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__8th__oiWgMb5Jeg]: hasVariant(
                    $state,
                    "others",
                    "_8th"
                  ),
                  [sty.spanothers__9th__oiWgMjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"Focused on"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span___8PkUf,
                {
                  [sty.spanothers__10th___8PkUfnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th___8PkUfxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th___8PkUf8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__9th___8PkUfjynmL]: hasVariant(
                    $state,
                    "others",
                    "_9th"
                  )
                }
              )}
            >
              {"clear solutions"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__cfocG,
                {
                  [sty.spanothers__10th__cfocGnFrSj]: hasVariant(
                    $state,
                    "others",
                    "_10th"
                  ),
                  [sty.spanothers__11Th__cfocGxdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__cfocG8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  ),
                  [sty.spanothers__1st__cfocGwDAe]: hasVariant(
                    $state,
                    "others",
                    "_1st"
                  )
                }
              )}
            >
              {"that move"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__kwp91,
                {
                  [sty.spanothers__11Th__kwp91XdSwz]: hasVariant(
                    $state,
                    "others",
                    "_11Th"
                  ),
                  [sty.spanothers__12Th__kwp918KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"your business"}
            </span>
          }
          <React.Fragment> </React.Fragment>
          {
            <span
              className={classNames(
                projectcss.all,
                projectcss.span,
                projectcss.__wab_text,
                projectcss.plasmic_default__inline,
                sty.span__jwfUb,
                {
                  [sty.spanothers__12Th__jwfUb8KXpD]: hasVariant(
                    $state,
                    "others",
                    "_12Th"
                  )
                }
              )}
            >
              {"forward"}
            </span>
          }
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </p>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header3: ["header3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSwitchingLetters__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSwitchingLetters__VariantsArgs;
    args?: PlasmicSwitchingLetters__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSwitchingLetters__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSwitchingLetters__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSwitchingLetters__ArgProps,
          internalVariantPropNames: PlasmicSwitchingLetters__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSwitchingLetters__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header3") {
    func.displayName = "PlasmicSwitchingLetters";
  } else {
    func.displayName = `PlasmicSwitchingLetters.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchingLetters = Object.assign(
  // Top-level PlasmicSwitchingLetters renders the root element
  makeNodeComponent("header3"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSwitchingLetters
    internalVariantProps: PlasmicSwitchingLetters__VariantProps,
    internalArgProps: PlasmicSwitchingLetters__ArgProps
  }
);

export default PlasmicSwitchingLetters;
/* prettier-ignore-end */
