/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: ZHPtj2-fhATx

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicShrinkcontainer.module.css"; // plasmic-import: ZHPtj2-fhATx/css

createPlasmicElementProxy;

export type PlasmicShrinkcontainer__VariantMembers = {
  others:
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th";
};
export type PlasmicShrinkcontainer__VariantsArgs = {
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
  >;
};
type VariantPropType = keyof PlasmicShrinkcontainer__VariantsArgs;
export const PlasmicShrinkcontainer__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicShrinkcontainer__ArgsType = {
  scrollShrink2?: React.ReactNode;
};
type ArgPropType = keyof PlasmicShrinkcontainer__ArgsType;
export const PlasmicShrinkcontainer__ArgProps = new Array<ArgPropType>(
  "scrollShrink2"
);

export type PlasmicShrinkcontainer__OverridesType = {
  scrollShrink?: Flex__<"div">;
};

export interface DefaultShrinkcontainerProps {
  scrollShrink2?: React.ReactNode;
  others?: SingleChoiceArg<
    | "_1st"
    | "_2nd"
    | "_3rd"
    | "_4th"
    | "_5th"
    | "_6th"
    | "_7th"
    | "_8th"
    | "_9th"
    | "_10th"
    | "_11Th"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShrinkcontainer__RenderFunc(props: {
  variants: PlasmicShrinkcontainer__VariantsArgs;
  args: PlasmicShrinkcontainer__ArgsType;
  overrides: PlasmicShrinkcontainer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"scrollShrink"}
      data-plasmic-override={overrides.scrollShrink}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.scrollShrink,
        {
          [sty.scrollShrinkothers__10th]: hasVariant($state, "others", "_10th"),
          [sty.scrollShrinkothers__11Th]: hasVariant($state, "others", "_11Th"),
          [sty.scrollShrinkothers__1st]: hasVariant($state, "others", "_1st"),
          [sty.scrollShrinkothers__2nd]: hasVariant($state, "others", "_2nd"),
          [sty.scrollShrinkothers__3rd]: hasVariant($state, "others", "_3rd"),
          [sty.scrollShrinkothers__4th]: hasVariant($state, "others", "_4th"),
          [sty.scrollShrinkothers__5th]: hasVariant($state, "others", "_5th"),
          [sty.scrollShrinkothers__6th]: hasVariant($state, "others", "_6th"),
          [sty.scrollShrinkothers__7th]: hasVariant($state, "others", "_7th"),
          [sty.scrollShrinkothers__8th]: hasVariant($state, "others", "_8th"),
          [sty.scrollShrinkothers__9th]: hasVariant($state, "others", "_9th")
        }
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.freeBox__tEx0Z)}>
            <div className={classNames(projectcss.all, sty.freeBox___9Gp5G)}>
              <div className={classNames(projectcss.all, sty.freeBox___5EL03)}>
                <div className={classNames(projectcss.all, sty.freeBox__r7GEr)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i07Kf
                    )}
                  >
                    {"Economics\nbefore formality."}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eCX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xvlp7
                    )}
                  >
                    {
                      "We map price, timeline, and real risks first and draft only what creates leverage."
                    }
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__xfpOx)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8Fz4J)}
                />
              </div>
            </div>
          </div>
        ),
        value: args.scrollShrink2
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  scrollShrink: ["scrollShrink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  scrollShrink: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShrinkcontainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShrinkcontainer__VariantsArgs;
    args?: PlasmicShrinkcontainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicShrinkcontainer__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicShrinkcontainer__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShrinkcontainer__ArgProps,
          internalVariantPropNames: PlasmicShrinkcontainer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShrinkcontainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "scrollShrink") {
    func.displayName = "PlasmicShrinkcontainer";
  } else {
    func.displayName = `PlasmicShrinkcontainer.${nodeName}`;
  }
  return func;
}

export const PlasmicShrinkcontainer = Object.assign(
  // Top-level PlasmicShrinkcontainer renders the root element
  makeNodeComponent("scrollShrink"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicShrinkcontainer
    internalVariantProps: PlasmicShrinkcontainer__VariantProps,
    internalArgProps: PlasmicShrinkcontainer__ArgProps
  }
);

export default PlasmicShrinkcontainer;
/* prettier-ignore-end */
