/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: cXr2yxWZ-dl9

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicCustomFirldCont.module.css"; // plasmic-import: cXr2yxWZ-dl9/css

createPlasmicElementProxy;

export type PlasmicCustomFirldCont__VariantMembers = {
  others: "email" | "message";
};
export type PlasmicCustomFirldCont__VariantsArgs = {
  others?: SingleChoiceArg<"email" | "message">;
};
type VariantPropType = keyof PlasmicCustomFirldCont__VariantsArgs;
export const PlasmicCustomFirldCont__VariantProps = new Array<VariantPropType>(
  "others"
);

export type PlasmicCustomFirldCont__ArgsType = { children?: React.ReactNode };
type ArgPropType = keyof PlasmicCustomFirldCont__ArgsType;
export const PlasmicCustomFirldCont__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicCustomFirldCont__OverridesType = {
  root?: Flex__<"div">;
  assistiveText6?: Flex__<"div">;
};

export interface DefaultCustomFirldContProps {
  children?: React.ReactNode;
  others?: SingleChoiceArg<"email" | "message">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCustomFirldCont__RenderFunc(props: {
  variants: PlasmicCustomFirldCont__VariantsArgs;
  args: PlasmicCustomFirldCont__ArgsType;
  overrides: PlasmicCustomFirldCont__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootothers_email]: hasVariant($state, "others", "email"),
          [sty.rootothers_message]: hasVariant($state, "others", "message")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__nvxFw)}>
        <div
          data-plasmic-name={"assistiveText6"}
          data-plasmic-override={overrides.assistiveText6}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.assistiveText6,
            {
              [sty.assistiveText6others_email]: hasVariant(
                $state,
                "others",
                "email"
              ),
              [sty.assistiveText6others_message]: hasVariant(
                $state,
                "others",
                "message"
              )
            }
          )}
        >
          {hasVariant($state, "others", "message")
            ? "Your message"
            : hasVariant($state, "others", "email")
              ? "Your email"
              : "Your name"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__yXxam)}>
        {renderPlasmicSlot({
          defaultContents: (
            <FormItemWrapper
              className={classNames("__wab_instance", sty.formField__miOEv)}
              label={null}
              name={"name"}
            >
              <div className={classNames(projectcss.all, sty.freeBox__mtloy)}>
                {(() => {
                  const child$Props = {
                    bordered: false,
                    className: classNames("__wab_instance", sty.input__zoLm7),
                    placeholder: "John Smith",
                    size: "large"
                  };

                  return <AntdInput {...child$Props} />;
                })()}
              </div>
            </FormItemWrapper>
          ),
          value: args.children
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "assistiveText6"],
  assistiveText6: ["assistiveText6"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  assistiveText6: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCustomFirldCont__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCustomFirldCont__VariantsArgs;
    args?: PlasmicCustomFirldCont__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCustomFirldCont__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCustomFirldCont__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCustomFirldCont__ArgProps,
          internalVariantPropNames: PlasmicCustomFirldCont__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCustomFirldCont__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCustomFirldCont";
  } else {
    func.displayName = `PlasmicCustomFirldCont.${nodeName}`;
  }
  return func;
}

export const PlasmicCustomFirldCont = Object.assign(
  // Top-level PlasmicCustomFirldCont renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    assistiveText6: makeNodeComponent("assistiveText6"),

    // Metadata about props expected for PlasmicCustomFirldCont
    internalVariantProps: PlasmicCustomFirldCont__VariantProps,
    internalArgProps: PlasmicCustomFirldCont__ArgProps
  }
);

export default PlasmicCustomFirldCont;
/* prettier-ignore-end */
