/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ou8ThpfYS6VZUK1hbxLRXQ
// Component: 3k_BHnJBdi4l

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: ou8ThpfYS6VZUK1hbxLRXQ/projectcss
import sty from "./PlasmicTurningCards2.module.css"; // plasmic-import: 3k_BHnJBdi4l/css

createPlasmicElementProxy;

export type PlasmicTurningCards2__VariantMembers = {
  others: "_1st" | "_2nd" | "_3rd";
  open: "open";
};
export type PlasmicTurningCards2__VariantsArgs = {
  others?: SingleChoiceArg<"_1st" | "_2nd" | "_3rd">;
  open?: SingleBooleanChoiceArg<"open">;
};
type VariantPropType = keyof PlasmicTurningCards2__VariantsArgs;
export const PlasmicTurningCards2__VariantProps = new Array<VariantPropType>(
  "others",
  "open"
);

export type PlasmicTurningCards2__ArgsType = {};
type ArgPropType = keyof PlasmicTurningCards2__ArgsType;
export const PlasmicTurningCards2__ArgProps = new Array<ArgPropType>();

export type PlasmicTurningCards2__OverridesType = {
  root?: Flex__<"div">;
  group1321315481?: Flex__<"div">;
  group1321315480?: Flex__<"div">;
  group1321315433?: Flex__<"div">;
  rectangle271?: Flex__<"div">;
  bluePoolCapital?: Flex__<"div">;
  asLeadInvestorInThe80MSeriesFOfGyg?: Flex__<"div">;
  image5?: Flex__<"div">;
  group1321315479?: Flex__<"div">;
  group1321315458?: Flex__<"div">;
  rectangle272?: Flex__<"div">;
  marinaCapital?: Flex__<"div">;
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech?: Flex__<"div">;
  image9?: Flex__<"div">;
  group1321315478?: Flex__<"div">;
  group1321315457?: Flex__<"div">;
  rectangle273?: Flex__<"div">;
  jetpackStudio?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition?: Flex__<"div">;
  group1321315459?: Flex__<"div">;
  rectangle217?: Flex__<"div">;
  image22?: Flex__<"div">;
  _1st2?: Flex__<"div">;
  image24?: Flex__<"div">;
  jetpackStudio5?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5?: Flex__<"div">;
  _2nd2?: Flex__<"div">;
  image11?: Flex__<"div">;
  jetpackStudio6?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6?: Flex__<"div">;
  _3rd2?: Flex__<"div">;
  image7?: Flex__<"div">;
  jetpackStudio7?: Flex__<"div">;
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7?: Flex__<"div">;
};

export interface DefaultTurningCards2Props {
  others?: SingleChoiceArg<"_1st" | "_2nd" | "_3rd">;
  open?: SingleBooleanChoiceArg<"open">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTurningCards2__RenderFunc(props: {
  variants: PlasmicTurningCards2__VariantsArgs;
  args: PlasmicTurningCards2__ArgsType;
  overrides: PlasmicTurningCards2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "others",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.others
      },
      {
        path: "open",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.open
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootothers__2nd]: hasVariant($state, "others", "_2nd"),
          [sty.rootothers__3rd]: hasVariant($state, "others", "_3rd")
        }
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__s3ZJ)}>
        <div
          data-plasmic-name={"group1321315481"}
          data-plasmic-override={overrides.group1321315481}
          className={classNames(projectcss.all, sty.group1321315481)}
        >
          <div
            data-plasmic-name={"group1321315480"}
            data-plasmic-override={overrides.group1321315480}
            className={classNames(projectcss.all, sty.group1321315480)}
          >
            <div
              data-plasmic-name={"group1321315433"}
              data-plasmic-override={overrides.group1321315433}
              className={classNames(projectcss.all, sty.group1321315433)}
            >
              <div
                data-plasmic-name={"rectangle271"}
                data-plasmic-override={overrides.rectangle271}
                className={classNames(projectcss.all, sty.rectangle271)}
              />

              <div
                data-plasmic-name={"bluePoolCapital"}
                data-plasmic-override={overrides.bluePoolCapital}
                className={classNames(projectcss.all, sty.bluePoolCapital)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8Mq3
                  )}
                >
                  {"blue pool capital"}
                </div>
              </div>
              <div
                data-plasmic-name={"asLeadInvestorInThe80MSeriesFOfGyg"}
                data-plasmic-override={
                  overrides.asLeadInvestorInThe80MSeriesFOfGyg
                }
                className={classNames(
                  projectcss.all,
                  sty.asLeadInvestorInThe80MSeriesFOfGyg
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__br7Se
                  )}
                >
                  {"as Lead Investor in the\n\u20ac80m Series F of GYG"}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(projectcss.all, sty.image5)}
            />
          </div>
          <div
            data-plasmic-name={"group1321315479"}
            data-plasmic-override={overrides.group1321315479}
            className={classNames(projectcss.all, sty.group1321315479)}
          >
            <div
              data-plasmic-name={"group1321315458"}
              data-plasmic-override={overrides.group1321315458}
              className={classNames(projectcss.all, sty.group1321315458)}
            >
              <div
                data-plasmic-name={"rectangle272"}
                data-plasmic-override={overrides.rectangle272}
                className={classNames(projectcss.all, sty.rectangle272)}
              />

              <div
                data-plasmic-name={"marinaCapital"}
                data-plasmic-override={overrides.marinaCapital}
                className={classNames(projectcss.all, sty.marinaCapital)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cHBiV
                  )}
                >
                  {"Marina Capital"}
                </div>
              </div>
              <div
                data-plasmic-name={
                  "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
                }
                data-plasmic-override={
                  overrides.onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech
                }
                className={classNames(
                  projectcss.all,
                  sty.onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wtux9
                  )}
                >
                  {
                    "on its bespoke founding investment in Rokksta\n- German mining Tech."
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"image9"}
              data-plasmic-override={overrides.image9}
              className={classNames(projectcss.all, sty.image9)}
            />
          </div>
          <div
            data-plasmic-name={"group1321315478"}
            data-plasmic-override={overrides.group1321315478}
            className={classNames(projectcss.all, sty.group1321315478)}
          >
            <div
              data-plasmic-name={"group1321315457"}
              data-plasmic-override={overrides.group1321315457}
              className={classNames(projectcss.all, sty.group1321315457)}
            >
              <div
                data-plasmic-name={"rectangle273"}
                data-plasmic-override={overrides.rectangle273}
                className={classNames(projectcss.all, sty.rectangle273)}
              />

              <div
                data-plasmic-name={"jetpackStudio"}
                data-plasmic-override={overrides.jetpackStudio}
                className={classNames(projectcss.all, sty.jetpackStudio)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vXtIc
                  )}
                >
                  {"Jetpack Studio"}
                </div>
              </div>
              <div
                data-plasmic-name={
                  "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
                }
                data-plasmic-override={
                  overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition
                }
                className={classNames(
                  projectcss.all,
                  sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition
                )}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sv45A
                  )}
                >
                  {
                    "GmbH in connection with multiple investments such as Merlin Digital Solutions, Rooms Technologies, Glorya , NOBS Nutrition."
                  }
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"group1321315459"}
              data-plasmic-override={overrides.group1321315459}
              className={classNames(projectcss.all, sty.group1321315459)}
            >
              <div
                data-plasmic-name={"rectangle217"}
                data-plasmic-override={overrides.rectangle217}
                className={classNames(projectcss.all, sty.rectangle217)}
              />

              <div
                data-plasmic-name={"image22"}
                data-plasmic-override={overrides.image22}
                className={classNames(projectcss.all, sty.image22)}
              />
            </div>
          </div>
        </div>
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__aPay, {
          [sty.freeBoxopen__aPay4GtRs]: hasVariant($state, "open", "open"),
          [sty.freeBoxothers__1st__aPaySmbpu]: hasVariant(
            $state,
            "others",
            "_1st"
          ),
          [sty.freeBoxothers__2nd__aPaYm1AQ]: hasVariant(
            $state,
            "others",
            "_2nd"
          ),
          [sty.freeBoxothers__3rd__aPaYzAxk8]: hasVariant(
            $state,
            "others",
            "_3rd"
          )
        })}
      >
        <div
          data-plasmic-name={"_1st2"}
          data-plasmic-override={overrides._1st2}
          className={classNames(projectcss.all, sty._1St2, {
            [sty._1St2open]: hasVariant($state, "open", "open"),
            [sty._1St2others__1st]: hasVariant($state, "others", "_1st"),
            [sty._1St2others__2nd]: hasVariant($state, "others", "_2nd"),
            [sty._1St2others__3rd]: hasVariant($state, "others", "_3rd")
          })}
        >
          <div className={classNames(projectcss.all, sty.freeBox__pLYj)}>
            <div
              data-plasmic-name={"image24"}
              data-plasmic-override={overrides.image24}
              className={classNames(projectcss.all, sty.image24)}
            />
          </div>
          <div
            data-plasmic-name={"jetpackStudio5"}
            data-plasmic-override={overrides.jetpackStudio5}
            className={classNames(projectcss.all, sty.jetpackStudio5)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fc0Bc
              )}
            >
              {"Jetpack Studio"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iGqDp
              )}
            >
              {
                "GmbH in connection with multiple investments such as Merlin Digital Solutions, Rooms Technologies, Glorya , NOBS Nutrition."
              }
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"_2nd2"}
          data-plasmic-override={overrides._2nd2}
          className={classNames(projectcss.all, sty._2Nd2, {
            [sty._2Nd2open]: hasVariant($state, "open", "open"),
            [sty._2Nd2others__1st]: hasVariant($state, "others", "_1st"),
            [sty._2Nd2others__2nd]: hasVariant($state, "others", "_2nd"),
            [sty._2Nd2others__3rd]: hasVariant($state, "others", "_3rd")
          })}
        >
          <div
            data-plasmic-name={"image11"}
            data-plasmic-override={overrides.image11}
            className={classNames(projectcss.all, sty.image11, {
              [sty.image11others__3rd]: hasVariant($state, "others", "_3rd")
            })}
          />

          <div
            data-plasmic-name={"jetpackStudio6"}
            data-plasmic-override={overrides.jetpackStudio6}
            className={classNames(projectcss.all, sty.jetpackStudio6)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pLih
              )}
            >
              {"Marina Capital"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zvlvt
              )}
            >
              {
                "on its bespoke founding investment in Rokksta\n- German mining Tech."
              }
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"_3rd2"}
          data-plasmic-override={overrides._3rd2}
          className={classNames(projectcss.all, sty._3Rd2, {
            [sty._3Rd2open]: hasVariant($state, "open", "open"),
            [sty._3Rd2others__1st]: hasVariant($state, "others", "_1st"),
            [sty._3Rd2others__2nd]: hasVariant($state, "others", "_2nd"),
            [sty._3Rd2others__3rd]: hasVariant($state, "others", "_3rd")
          })}
        >
          <div
            data-plasmic-name={"image7"}
            data-plasmic-override={overrides.image7}
            className={classNames(projectcss.all, sty.image7)}
          />

          <div
            data-plasmic-name={"jetpackStudio7"}
            data-plasmic-override={overrides.jetpackStudio7}
            className={classNames(projectcss.all, sty.jetpackStudio7)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yAvA
              )}
            >
              {"blue pool capital"}
            </div>
          </div>
          <div
            data-plasmic-name={
              "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7"
            }
            data-plasmic-override={
              overrides.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7
            }
            className={classNames(
              projectcss.all,
              sty.gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7
            )}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rY4
              )}
            >
              {"as Lead Investor in the\n\u20ac80m Series F of GYG"}
            </div>
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "group1321315481",
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5",
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9",
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22",
    "_1st2",
    "image24",
    "jetpackStudio5",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5",
    "_2nd2",
    "image11",
    "jetpackStudio6",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6",
    "_3rd2",
    "image7",
    "jetpackStudio7",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7"
  ],
  group1321315481: [
    "group1321315481",
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5",
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9",
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22"
  ],
  group1321315480: [
    "group1321315480",
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg",
    "image5"
  ],
  group1321315433: [
    "group1321315433",
    "rectangle271",
    "bluePoolCapital",
    "asLeadInvestorInThe80MSeriesFOfGyg"
  ],
  rectangle271: ["rectangle271"],
  bluePoolCapital: ["bluePoolCapital"],
  asLeadInvestorInThe80MSeriesFOfGyg: ["asLeadInvestorInThe80MSeriesFOfGyg"],
  image5: ["image5"],
  group1321315479: [
    "group1321315479",
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech",
    "image9"
  ],
  group1321315458: [
    "group1321315458",
    "rectangle272",
    "marinaCapital",
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
  ],
  rectangle272: ["rectangle272"],
  marinaCapital: ["marinaCapital"],
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: [
    "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
  ],
  image9: ["image9"],
  group1321315478: [
    "group1321315478",
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition",
    "group1321315459",
    "rectangle217",
    "image22"
  ],
  group1321315457: [
    "group1321315457",
    "rectangle273",
    "jetpackStudio",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
  ],
  rectangle273: ["rectangle273"],
  jetpackStudio: ["jetpackStudio"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
    ],
  group1321315459: ["group1321315459", "rectangle217", "image22"],
  rectangle217: ["rectangle217"],
  image22: ["image22"],
  _1st2: [
    "_1st2",
    "image24",
    "jetpackStudio5",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5"
  ],
  image24: ["image24"],
  jetpackStudio5: ["jetpackStudio5"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5"
    ],
  _2nd2: [
    "_2nd2",
    "image11",
    "jetpackStudio6",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6"
  ],
  image11: ["image11"],
  jetpackStudio6: ["jetpackStudio6"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6"
    ],
  _3rd2: [
    "_3rd2",
    "image7",
    "jetpackStudio7",
    "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7"
  ],
  image7: ["image7"],
  jetpackStudio7: ["jetpackStudio7"],
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7:
    [
      "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7"
    ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  group1321315481: "div";
  group1321315480: "div";
  group1321315433: "div";
  rectangle271: "div";
  bluePoolCapital: "div";
  asLeadInvestorInThe80MSeriesFOfGyg: "div";
  image5: "div";
  group1321315479: "div";
  group1321315458: "div";
  rectangle272: "div";
  marinaCapital: "div";
  onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: "div";
  image9: "div";
  group1321315478: "div";
  group1321315457: "div";
  rectangle273: "div";
  jetpackStudio: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition: "div";
  group1321315459: "div";
  rectangle217: "div";
  image22: "div";
  _1st2: "div";
  image24: "div";
  jetpackStudio5: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5: "div";
  _2nd2: "div";
  image11: "div";
  jetpackStudio6: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6: "div";
  _3rd2: "div";
  image7: "div";
  jetpackStudio7: "div";
  gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTurningCards2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTurningCards2__VariantsArgs;
    args?: PlasmicTurningCards2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTurningCards2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTurningCards2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTurningCards2__ArgProps,
          internalVariantPropNames: PlasmicTurningCards2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTurningCards2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTurningCards2";
  } else {
    func.displayName = `PlasmicTurningCards2.${nodeName}`;
  }
  return func;
}

export const PlasmicTurningCards2 = Object.assign(
  // Top-level PlasmicTurningCards2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    group1321315481: makeNodeComponent("group1321315481"),
    group1321315480: makeNodeComponent("group1321315480"),
    group1321315433: makeNodeComponent("group1321315433"),
    rectangle271: makeNodeComponent("rectangle271"),
    bluePoolCapital: makeNodeComponent("bluePoolCapital"),
    asLeadInvestorInThe80MSeriesFOfGyg: makeNodeComponent(
      "asLeadInvestorInThe80MSeriesFOfGyg"
    ),
    image5: makeNodeComponent("image5"),
    group1321315479: makeNodeComponent("group1321315479"),
    group1321315458: makeNodeComponent("group1321315458"),
    rectangle272: makeNodeComponent("rectangle272"),
    marinaCapital: makeNodeComponent("marinaCapital"),
    onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech: makeNodeComponent(
      "onItsBespokeFoundingInvestmentInRokkstaGermanMiningTech"
    ),
    image9: makeNodeComponent("image9"),
    group1321315478: makeNodeComponent("group1321315478"),
    group1321315457: makeNodeComponent("group1321315457"),
    rectangle273: makeNodeComponent("rectangle273"),
    jetpackStudio: makeNodeComponent("jetpackStudio"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition"
      ),
    group1321315459: makeNodeComponent("group1321315459"),
    rectangle217: makeNodeComponent("rectangle217"),
    image22: makeNodeComponent("image22"),
    _1st2: makeNodeComponent("_1st2"),
    image24: makeNodeComponent("image24"),
    jetpackStudio5: makeNodeComponent("jetpackStudio5"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition5"
      ),
    _2nd2: makeNodeComponent("_2nd2"),
    image11: makeNodeComponent("image11"),
    jetpackStudio6: makeNodeComponent("jetpackStudio6"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition6"
      ),
    _3rd2: makeNodeComponent("_3rd2"),
    image7: makeNodeComponent("image7"),
    jetpackStudio7: makeNodeComponent("jetpackStudio7"),
    gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7:
      makeNodeComponent(
        "gmbHInConnectionWithMultipleInvestmentsSuchAsMerlinDigitalSolutionsRoomsTechnologiesGloryaNobsNutrition7"
      ),

    // Metadata about props expected for PlasmicTurningCards2
    internalVariantProps: PlasmicTurningCards2__VariantProps,
    internalArgProps: PlasmicTurningCards2__ArgProps
  }
);

export default PlasmicTurningCards2;
/* prettier-ignore-end */
