// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicNewsliding3Cards,
  DefaultNewsliding3CardsProps
} from "./plasmic/evangelisti_dev_1/PlasmicNewsliding3Cards";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Newsliding3CardsProps extends Omit<DefaultNewsliding3CardsProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultNewsliding3CardsProps altogether and have
// total control over the props for your component.
export interface Newsliding3CardsProps extends DefaultNewsliding3CardsProps {}

function Newsliding3Cards_(
  props: Newsliding3CardsProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicNewsliding3Cards to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicNewsliding3Cards are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Newsliding3CardsProps here, but feel free
  // to do whatever works for you.

  return <PlasmicNewsliding3Cards root={{ ref }} {...props} />;
}

const Newsliding3Cards = React.forwardRef(Newsliding3Cards_);
export default Newsliding3Cards;
