// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/evangelisti_dev_1/PlasmicGlobalContextsProvider";

import { PlasmicHomepage } from "../components/plasmic/evangelisti_dev_1/PlasmicHomepage";
import { useRouter } from "next/router";

function Homepage() {
  const router = useRouter();

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={router?.pathname}
        params={router?.query}
        query={router?.query}
      >
        <PlasmicHomepage />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Homepage;
